# Generated by Django 5.2.17 on 2026-09-01 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient", models.CharField(db_index=True, max_length=20)),
                ("purpose", models.CharField(default="authentication", max_length=50)),
                ("hashed_code", models.CharField(editable=False, max_length=64)),
                ("code_prefix", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("EXPIRED", "Expired"),
                            ("USED", "Used"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_requests",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "recipient"],
                        name="otp_otprequ_custome_2d3452_idx",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="otp_otprequ_status_1ffa59_idx",
                    ),
                ],
            },
        ),
    ]
