# Generated by Django 5.2.17 on 2026-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otprequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "طلب رمز تحقق",
                "verbose_name_plural": "طلبات رمز التحقق",
            },
        ),
        migrations.AlterField(
            model_name="otprequest",
            name="recipient",
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
