# Generated by Django 5.2.17 on 2026-09-02 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_options"),
        ("otp", "0002_alter_otprequest_options_alter_otprequest_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otprequest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_requests",
                to="customers.customer",
            ),
        ),
    ]
