# Generated by Django 5.2.17 on 2026-09-01 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "android_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("SUSPENDED", "Suspended"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="DISCONNECTED",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "battery_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("WIFI", "WiFi"),
                            ("MOBILE", "Mobile"),
                            ("ETHERNET", "Ethernet"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("auth_token", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "selection_policy",
                    models.CharField(default="least_used", max_length=30),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slot", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                ("carrier", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, default="", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REMOVED", "Removed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("sms_capability", models.BooleanField(default=True)),
                ("receive_capability", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sim_cards",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device", "slot"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["customer", "status"], name="devices_dev_custome_3a21b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "last_seen"], name="devices_dev_status_b6dd78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simcard",
            index=models.Index(
                fields=["device", "status"], name="devices_sim_device__9a7cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simcard",
            index=models.Index(
                fields=["phone_number"], name="devices_sim_phone_n_686b00_idx"
            ),
        ),
    ]
