# Generated by Django 5.2.17 on 2026-09-01 16:17

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("customers", "0001_initial"),
        ("devices", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RECEIVED", "Received"),
                            ("API_REQUEST", "API Request"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=core.utils.datetime_now
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="customers.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="devices.device",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="messaging.message",
                    ),
                ),
                (
                    "sim_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="devices.simcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "occurred_at"],
                        name="usage_usage_custome_351b86_idx",
                    ),
                    models.Index(
                        fields=["customer", "event_type", "occurred_at"],
                        name="usage_usage_custome_15b9af_idx",
                    ),
                    models.Index(
                        fields=["device", "occurred_at"],
                        name="usage_usage_device__dfdb74_idx",
                    ),
                    models.Index(
                        fields=["sim_card", "occurred_at"],
                        name="usage_usage_sim_car_5e4062_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("DAILY", "Daily"), ("MONTHLY", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                ("sent", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("received", models.PositiveIntegerField(default=0)),
                ("api_requests", models.PositiveIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_summaries",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("customer", "period", "period_start")},
            },
        ),
    ]
