# Generated by Django 5.2.17 on 2026-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagerecord",
            name="message",
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="message_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
