# Generated by Django 5.2.17 on 2026-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0002_remove_usagerecord_message_usagerecord_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagerecord",
            name="message_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
