# Generated by Django 5.2.17 on 2026-09-01 16:17

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("customers", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("recipient", models.CharField(db_index=True, max_length=20)),
                ("sender", models.CharField(blank=True, default="", max_length=20)),
                ("body", models.TextField()),
                (
                    "encoding",
                    models.CharField(
                        choices=[
                            ("GSM_7BIT", "GSM 7-bit"),
                            ("UCS_2", "UCS-2"),
                            ("AUTO", "Auto"),
                        ],
                        db_index=True,
                        default="AUTO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("ASSIGNED", "Assigned"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("sending_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_bulk", models.BooleanField(default=False)),
                (
                    "bulk_group_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customers.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="devices.device",
                    ),
                ),
                (
                    "sim_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="devices.simcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("ASSIGNED", "Assigned"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "device_job_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_attempts",
                        to="devices.device",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_records",
                        to="messaging.message",
                    ),
                ),
                (
                    "sim_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_attempts",
                        to="devices.simcard",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="IncomingMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("from_number", models.CharField(db_index=True, max_length=20)),
                ("to_number", models.CharField(db_index=True, max_length=20)),
                ("body", models.TextField()),
                ("received_at", models.DateTimeField(default=core.utils.datetime_now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("WEBHOOK_SENT", "Webhook Sent"),
                            ("WEBHOOK_FAILED", "Webhook Failed"),
                            ("IGNORED", "Ignored"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_messages",
                        to="customers.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_messages",
                        to="devices.device",
                    ),
                ),
                (
                    "sim_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_messages",
                        to="devices.simcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "received_at"],
                        name="messaging_i_custome_f131af_idx",
                    ),
                    models.Index(
                        fields=["from_number"], name="messaging_i_from_nu_87c5df_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["status", "priority"], name="messaging_m_status_a99744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["customer", "status"], name="messaging_m_custome_353e51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["customer", "created_at"], name="messaging_m_custome_11977d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient"], name="messaging_m_recipie_bf3df7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["idempotency_key", "customer"],
                name="messaging_m_idempot_af794d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["device", "status"], name="messaging_m_device__73a7b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattempt",
            index=models.Index(
                fields=["message", "status"], name="messaging_m_message_881684_idx"
            ),
        ),
    ]
