# Generated by Django 5.2.17 on 2026-09-01 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DISABLED", "Disabled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "rate_rps",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "rate_per_min",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "rate_per_hour",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "rate_per_day",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "rate_per_month",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("plan", models.CharField(default="free", max_length=50)),
                ("max_devices", models.PositiveIntegerField(default=10)),
                ("max_api_keys", models.PositiveIntegerField(default=10)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="customers_c_status_afd3e3_idx",
                    ),
                    models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
                ],
            },
        ),
    ]
