# Generated by Django 5.2.17 on 2026-09-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
            },
        ),
    ]
